steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/terraform', '.']
- name: 'gcr.io/${PROJECT_ID}/terraform'
  args: ['version']
images: ['gcr.io/${PROJECT_ID}/terraform']
tags: ['cloud-builders-community']
